---

- name: Setup
  hosts: localhost
  connection: local
  tasks:
    - name: ensure ssh directory exists
      file:
        path: "{{ item }}"
        state: directory
        mode: 0700
      with_items:
        - "./.ssh"
        - "~/.ssh"

    - name: import public SSH hostkeys
      known_hosts:
        path: ~/.ssh/known_hosts
        name: "{{ hostvars[item]['inventory_hostname'] }}"
        key: "{{ hostvars[item]['ansible_ssh_hostkey_pub'] }}"
      with_items:  "{{ groups['all'] }}"

    - name: import private SSH key
      ansible.builtin.copy:
        dest: "./.ssh/id_ed25519_cicd_rotebeete_org"
        content: "{{ ansible_ssh_key }}"
        mode: 0600

    - name: import public SSH key
      ansible.builtin.copy:
        dest: "./.ssh/id_ed25519_cicd_rotebeete_org.pub"
        content: "{{ ansible_ssh_key_pub }}"
        mode: 0600

- name: Deploy
  hosts: webservers
  vars:
    ansible_ssh_private_key_file: "./.ssh/id_ed25519_cicd_rotebeete_org"
  tasks:
    - block:
        - name: become | check the default priviledge escalation
          shell: "[ $(id -u) -eq 0 ]"
          changed_when: false

