name: test and deploy ansible playbook
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout codebase
        uses: actions/checkout@v2

      - name: execute ansible-lint
        uses: ./.github/actions/ansible
        with:
          entrypoint: ansible-lint

  deploy:
    runs-on: ubuntu-20.04
    needs: test
    steps:
      - name: checkout codebase
        uses: actions/checkout@v2

      - name: inject vault passphrase
        run: echo "${{ secrets.VAULT_PASS }}" > ./.vault_pass

      - name: execute ansible
        uses: ./.github/actions/ansible
        with:
          entrypoint: ansible-playbook
          args: playbook.yml

      - name: shred vault passphrase
        run: shred ./.vault_pass
