name: Test and Deploy Ansible playbook
on:
  push:
    branches: main
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE.md'

jobs:
  Lint:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Execute Ansible-Lint
        uses: docker://rotebeete/ansible:latest
        with:
          entrypoint: ansible-lint
          args: .

  Run:
    runs-on: ubuntu-20.04
    needs: Lint
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Execute Ansible
        uses: docker://rotebeete/ansible:latest
        with:
          entrypoint: ansible-playbook
          args: playbook.yml
        env:
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
