name: Master build and deploy
on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/ansible-lint
  deploy:
    runs-on: ubuntu-20.04
    needs: build
    steps:
    - uses: actions/checkout@v2
    - uses: ./.github/actions/ansible
      env:
        VAULT_PASS: ${{ secrets.VAULT_PASS }}