name: Test Ansible playbook
on:
  pull_request:
    branches: main
    paths-ignore:
      - '**/README.md'
      - '**/LICENSE.md'

jobs:
  Lint:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout codebase
        uses: actions/checkout@v2

      - name: Execute Ansible-Lint
        uses: docker://rotebeete/ansible:latest
        with:
          entrypoint: ansible-lint
          args: .
        env:
          ANSIBLE_FORCE_COLOR: '1'
          PY_COLORS: '1'

  Test:
    runs-on: ubuntu-20.04
    needs: Lint
    steps:
      - name: Checkout codebase
        uses: actions/checkout@v2

      - name: Execute Ansible Check
        uses: docker://rotebeete/ansible:latest
        with:
          entrypoint: ansible-playbook
          args: playbook.yml --check
        env:
          ANSIBLE_FORCE_COLOR: '1'
          PY_COLORS: '1'
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
